[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fair_tickets = "Ggb46RAz1cWos2fQp4eWorFPpjPWouTBzccyCDVMGcgU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
