[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_rbac = "8VF17ZETUYhtM4omTTgUa6ghESD7J9L9tcG5FJmMkoa2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
